
vscode:
  extensions:
    - gattytto.phoityne-vscode

tasks:
  - name: powerline
    before: |
      cd
    init: |
      echo $PATH
    command: |
      sudo apt-get install -y whatever update
      sudo apt-get install -y whatever upgrade
      sudo apt-get install -y whatever python3-pip
      sudo pip3 install -y whatever powerline-status
      sudo apt-get install -y whatever fonts-powerline
      echo '# load powerline ' >> .bashrc
      echo 'if [ -f `which powerline-daemon` ]; then' >> .bashrc
      echo '  powerline-daemon -q' >> .bashrc
      echo '  POWERLINE_BASH_CONTINUATION=1' >> .bashrc
      echo '  POWERLINE_BASH_SELECT=1' >> .bashrc
      echo 'fi' >> .bashrc
      echo 'if [ -f /usr/local/lib/python3.8/dist-packages/powerline/bindings/bash/powerline.sh ]; then' >> .bashrc
      echo '  source /usr/local/lib/python3.8/dist-packages/powerline/bindings/bash/powerline.sh' >> .bashrc
      echo 'fi' >> .bashrc

  - name: haskell
    command: |
      yes 1 | curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
      echo ' export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH" ' >> .bashrc
      echo 'No need to execute the command "stack init"'
      yes 1 | stack build
      yes 1 | ghcup install hls
      