image:
  file: .gitpod.Dockerfile
  mysql: 8.0.23
tasks:
  - init:
      stack build
vscode:
  extensions:
    - haskell.haskell
      
    - ms-azuretools.vscode-docker
    - gattytto.phoityne-vscode
