
vscode:
  extensions:
    - gattytto.phoityne-vscode

tasks:
  - name: powerline
    before: |
      cd
    init: |
      echo $PATH
    command: |
      sudo apt-get install python3-pip
      sudo pip3 install powerline-status
      sudo apt-get install fonts-powerline
      yes 1 | command
      echo '# load powerline ' >> .bashrc
      echo '# load powerline ' >> .bashrc

  - name: haskell
    command: |
      curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
      yes 1 | command
      export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
      echo 'No need to execute the command "stack init"'
      stack build
      ghcup install hls
      